# Cheat sheet:

# client.drop_database(database_name)
# client.database_names()
# client.list_databases()
# client.list_database_names()
#
# db.name
# db.create_collection(name, options)
# db.drop_collection(name_or_collection)
# db.list_collection_names()
# db.list_collections()
#
# db.collection.bulk_write(requests)        # Send a batch of write operations to the server
# db.collection.insert_one(document)
# db.collection.insert_many(documents)
# db.collection.replace_one(filter, replacement)
# db.collection.update_one(filter, update)
# db.collection.update_many(filter, update)
# db.collection.delete_one(filter)
# db.collection.delete_many(filter)
# db.collection.aggregate(pipeline)
# db.collection.find_one(filter, ...)
# db.collection.find_one_and_delete(filter, ...)
# db.collection.find_one_and_replace(filter, replacement, ...)
# db.collection.find_one_and_update(filter, update, ...)
# db.collection.count_documents(filter)
# db.collection.estimated_document_count()
# db.collection.distinct(key, ...)
# db.collection.create_index(keys)
# db.collection.create_indexes(indexes)
# db.collection.drop_index(index_or_name)
# db.collection.drop_indexes()
# db.collection.reindex()
# db.collection.list_indexes()
# db.collection.index_information()
# db.collection.drop()
# db.collection.rename(new_name)
# db.collection.options()
# db.collection.map_reduce(map, reduce, out)
